import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

interface Item {
  type: string;
  items?: Item | Item[];
}

interface Schema {
  properties: Record<string, Item>;
  required: string[];
}

const base = "https://swapi.info/api";
const params = ["films", "people", "planets", "species", "starships", "vehicles"] as const;

const outputDir = path.join(import.meta.dirname, "..", "types");
const output = path.join(outputDir, "swapi.ts");

function pascalCase(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function toTsType(property: Item): string {
  switch (property.type) {
    case "string":
      return "string";

    case "integer":
    case "number":
      return "number";

    case "boolean":
      return "boolean";

    case "array": {
      const items = Array.isArray(property.items) ? property.items[0] : property.items;
      return `${items ? toTsType(items) : "unknown"}[]`;
    }

    case "object":
      return "Record<string, unknown>";

    default:
      return "unknown";
  }
}

function buildInterface(name: string, schema: Schema): string {
  // set for fast lookup
  const required = new Set(schema.required);

  const fields = Object.entries(schema.properties).map(([key, property]) => {
    const optional = required.has(key) ? "" : "?";
    return `  ${key}${optional}: ${toTsType(property)};`;
  });

  return `export interface ${pascalCase(name)} {\n${fields.join("\n")}\n}`;
}

(async () => {
  try {
    const interfaces = await Promise.all(
      params.map(async (resource) => {
        const res = await fetch(`${base}/${resource}/schema`);
        if (!res.ok) throw new Error(`Failed to fetch ${resource} schema: ${res.status}`);

        const schema = (await res.json()) as Schema;
        console.debug(schema);
        return buildInterface(resource, schema);
      }),
    );

    const banner = "// Generated by scripts/generateTypes.ts — do not edit by hand.\n\n";
    await mkdir(outputDir, { recursive: true });
    await writeFile(output, banner + interfaces.join("\n\n") + "\n");

    console.log(`Wrote ${params.length} interfaces to ${output}`);
  } catch (error) {
    console.error("Unable to generate types", error);
  }
})();
